export const FETCH_MOVIE_REQUEST_START = 'FETCH_MOVIE_REQUEST_START';
export const FETCH_MOVIE_REQUEST_SUCCESS = 'FETCH_MOVIE_REQUEST_SUCCESS';
export const FETCH_MOVIE_REQUEST_ERROR = 'FETCH_MOVIE_REQUEST_ERROR';
