export const movies = {
  page: 1,
  total_results: 396824,
  total_pages: 19842,
  results: [
    {
      vote_count: 2191,
      id: 297802,
      video: false,
      vote_average: 6.9,
      title: 'Аквамен',
      popularity: 513.81,
      poster_path: '/fk6y3eWV1vFwZOY5k9IXecEpLyu.jpg',
      original_language: 'en',
      original_title: 'Aquaman',
      genre_ids: [28, 14, 878, 12],
      backdrop_path: '/5A2bMlLfJrAfX9bqAibOL2gCruF.jpg',
      adult: false,
      overview:
        'Действие фильма разворачивается в необъятном и захватывающем подводном мире семи морей, а сюжет знакомит зрителей с историей происхождения получеловека-полуатланта Артура Карри и ключевыми событиями его жизни — теми, что заставят его не только столкнуться с самим собой, но и выяснить, достоин ли он быть тем, кем ему суждено… царем!',
      release_date: '2018-12-07'
    },
    {
      vote_count: 644,
      id: 424783,
      video: false,
      vote_average: 6.6,
      title: 'Бамблби',
      popularity: 332.176,
      poster_path: '/2k9nXxST186qGgvs7CO0yrPI3Yf.jpg',
      original_language: 'en',
      original_title: 'Bumblebee',
      genre_ids: [28, 12, 878],
      backdrop_path: '/8bZ7guF94ZyCzi7MLHzXz6E5Lv8.jpg',
      adult: false,
      overview:
        '1987 год. Скрываясь от преследования, Бамблби находит убежище на автомобильной свалке в калифорнийском городке, где живет Чарли. Девушке скоро исполнится 18, она стремится найти свое место в жизни. И именно она наталкивается на покореженного и сломленного Бамблби. Приведя его в чувство, Чарли моментально осознает: на ее пути оказался не простой желтый Фольксваген Жук…',
      release_date: '2018-12-15'
    },
    {
      vote_count: 536,
      id: 400650,
      video: false,
      vote_average: 6.8,
      title: 'Мэри Поппинс возвращается',
      popularity: 202.796,
      poster_path: '/uUm76WfwQXWhHH2T2ZGLa03tVsZ.jpg',
      original_language: 'en',
      original_title: 'Mary Poppins Returns',
      genre_ids: [14, 10402, 10751, 35],
      backdrop_path: '/cwiJQXezWz876K3jS57Sq56RYCZ.jpg',
      adult: false,
      overview:
        'Фильм рассказывает о новых приключениях Мэри и ее друга Джека, которым предстоит встретиться с представителями следующего поколения семейства Бэнкс.',
      release_date: '2018-12-19'
    },
    {
      vote_count: 2570,
      id: 405774,
      video: false,
      vote_average: 7.2,
      title: 'Птичий короб',
      popularity: 184.5,
      poster_path: '/rGfGfgL2pEPCfhIvqHXieXFn7gp.jpg',
      original_language: 'en',
      original_title: 'Bird Box',
      genre_ids: [53, 18, 878, 27],
      backdrop_path: '/z6m7s4w4Erxnr5k2jc1TZR1AMva.jpg',
      adult: false,
      overview:
        'Мать-одиночка с двумя детьми решается наконец бежать из своего дома-тюрьмы – бежать туда, где по слухам еще есть люди, туда где безопасно. Ей предстоит ужасное испытание: двадцать миль вниз по реке в ненадежной лодке, с завязанными глазами, полагаясь лишь на острый слух ее малышей. Четырехлетних детей, которые росли и учились различать звуки в темноте маленьких душных комнат. Одно неверное движение – и они обречены. Кто-то ходит рядом, кто-то постоянно следит за ними – обычное животное или монстр?',
      release_date: '2018-12-13'
    },
    {
      vote_count: 117,
      id: 504172,
      video: false,
      vote_average: 6.2,
      title: 'Наркокурьер',
      popularity: 183.317,
      poster_path: '/t0idiLMalKMj2pLsvqHrOM4LPdQ.jpg',
      original_language: 'en',
      original_title: 'The Mule',
      genre_ids: [80, 18, 53],
      backdrop_path: '/bkc4AY6FTa3yNqrshE9b1elDzPt.jpg',
      adult: false,
      overview:
        'Эрл Стоун - одинокий старик. Его частный бизнес находится на грани разорения, отношения с женой не ладятся, а дети, кажется, давно забыли о его существовании. Неожиданно ему предлагают не пыльную, но прибыльную работенку - просто водить машину. Стоун поначалу соглашается и вскоре понимает, что стал наркокурьером мексиканского картеля и попал в поле зрения оперативника Агентства по контролю за оборотом наркотиков.',
      release_date: '2018-12-14'
    },
    {
      vote_count: 920,
      id: 324857,
      video: false,
      vote_average: 8.5,
      title: 'Человек-паук: Через вселенные',
      popularity: 167.681,
      poster_path: '/dEh3ksfCPRp41Q6RPkIjI64Zfr1.jpg',
      original_language: 'en',
      original_title: 'Spider-Man: Into the Spider-Verse',
      genre_ids: [28, 12, 16, 878, 35],
      backdrop_path: '/e7CE5vx4KqUuz0peKdHRVZB0Pn8.jpg',
      adult: false,
      overview:
        'В центре сюжета уникальной и инновационной в визуальном плане картины подросток из Нью-Йорка Майлз Моралес, который живет в мире безграничных возможностей вселенных Человека-паука, где костюм супергероя носит не только он.',
      release_date: '2018-12-07'
    },
    {
      vote_count: 4153,
      id: 335983,
      video: false,
      vote_average: 6.5,
      title: 'Веном',
      popularity: 154.742,
      poster_path: '/8Gyl0fknqiZeCLm9XitxCXQmEL9.jpg',
      original_language: 'en',
      original_title: 'Venom',
      genre_ids: [878],
      backdrop_path: '/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg',
      adult: false,
      overview:
        'В центре сюжета — Веном, один из самых известных супергероев вселенной Человека-паука. Это симбиот, разумное существо инопланетного происхождения, которое вселяется в тело журналиста Эдди Брока.',
      release_date: '2018-09-28'
    },
    {
      vote_count: 483,
      id: 480530,
      video: false,
      vote_average: 6.4,
      title: 'Крид 2',
      popularity: 149.677,
      poster_path: '/dDwlCo3vXd2606XIYMqGssKfMo8.jpg',
      original_language: 'en',
      original_title: 'Creed II',
      genre_ids: [18, 28],
      backdrop_path: '/8yqLPNwNCtpOPc3XkOlkSMnghzw.jpg',
      adult: false,
      overview:
        'Фильм рассказывает о возвращении на ринг боксера Адониса Крида, тренером которого выступает легендарный Рокки.',
      release_date: '2018-11-20'
    },
    {
      vote_count: 134,
      id: 429197,
      video: false,
      vote_average: 7.1,
      title: 'Власть',
      popularity: 141.033,
      poster_path: '/kfyCU0qerZX3IzFpRkbsdCH5UHS.jpg',
      original_language: 'en',
      original_title: 'Vice',
      genre_ids: [18, 36, 35],
      backdrop_path: '/uvy89JLcYEiUb0VOoSjkUrIW3nJ.jpg',
      adult: false,
      overview:
        'Фильм рассказывает о 46-м вице-президенте США Дике Чейни, который признается одним из самых влиятельных вице-президентов в истории Соединенных Штатов.',
      release_date: '2018-12-25'
    },
    {
      vote_count: 2823,
      id: 338952,
      video: false,
      vote_average: 6.9,
      title: 'Фантастические твари: Преступление Грин-де-Вальда',
      popularity: 134.566,
      poster_path: '/4wH16yc3Rmpx8Ob33QTJkFVNf5j.jpg',
      original_language: 'en',
      original_title: 'Fantastic Beasts: The Crimes of Grindelwald',
      genre_ids: [10751, 14, 12],
      backdrop_path: '/wDN3FIcQQ1HI7mz1OOKYHSQtaiE.jpg',
      adult: false,
      overview:
        'В конце первого фильма могущественный темный волшебник Геллерт Грин-де-Вальд был пойман сотрудниками МАКУСА (Магического Конгресса Управления по Северной Америке), не без помощи Ньюта Саламандера. Выполняя свое обещание, темный маг устраивает грандиозный побег и начинает собирать сторонников, большинство из которых не знают о его истинной цели: добиться превосходства волшебников над всеми немагическими существами на планете. Чтобы сорвать планы Грин-де-Вальда, Альбус Дамблдор обращается к своему бывшему студенту Ньюту Саламандеру, который соглашается помочь, не подозревая, какая опасность ему грозит. В раскалывающемся на части волшебном мире любовь и верность проверяются на прочность, а конфликт разделяет даже настоящих друзей и членов семей.',
      release_date: '2018-11-14'
    },
    {
      vote_count: 692,
      id: 404368,
      video: false,
      vote_average: 7.5,
      title: 'Ральф против интернета',
      popularity: 116.1,
      poster_path: '/tVmomifGhoJfijkOnSGDDZwRSH5.jpg',
      original_language: 'en',
      original_title: 'Ralph Breaks the Internet',
      genre_ids: [10751, 16, 35, 14],
      backdrop_path: '/88poTBTafMXaz73vYi3c74g0y2k.jpg',
      adult: false,
      overview:
        'Ральф отправляется в путешествие по Интернету, чтобы починить «Сладкий Форсаж».',
      release_date: '2018-11-20'
    },
    {
      vote_count: 114,
      id: 503314,
      video: false,
      vote_average: 7.3,
      title: 'Драконий жемчуг: Супер (Броли)',
      popularity: 115.989,
      poster_path: '/518jdIQHCZmYqIcNCaqbZuDRheV.jpg',
      original_language: 'ja',
      original_title: 'ドラゴンボール超スーパー ブロリー',
      genre_ids: [28, 16, 878],
      backdrop_path: '/6OTRuxpwUUGbmCX3MKP25dOmo59.jpg',
      adult: false,
      overview:
        'Тема этого замечательного нового фильма будет «Сайян», самая сильная раса во вселенной. Начиная с «Битвы богов», Гокуу претерпел новые формы от Бога Супер Сайяна до Супер Сайяна Блу в других эволюционированных формах, которые выросли против многих непобедимых воинов из нескольких вселенных. Эта новая история будет сфокусирована на происхождении силы сайян и что значит быть Сайаном.',
      release_date: '2018-12-14'
    },
    {
      vote_count: 29,
      id: 567604,
      video: false,
      vote_average: 7.9,
      title: 'Жил-был Дэдпул',
      popularity: 108.978,
      poster_path: '/pxqy5RGG05G1jfsi2mSwkKe8FwQ.jpg',
      original_language: 'en',
      original_title: 'Once Upon a Deadpool',
      genre_ids: [35, 28],
      backdrop_path: '/djah5gSgqzIbMj2SU0Ljj8Xo2pT.jpg',
      adult: false,
      overview:
        'Старая история о Болтливом наемнике, пересказанная на новый лад.',
      release_date: '2018-12-11'
    },
    {
      vote_count: 10642,
      id: 299536,
      video: false,
      vote_average: 8.3,
      title: 'Мстители: Война бесконечности',
      popularity: 106.677,
      poster_path: '/qIUFg6tzKeK5bUDguonWCAFceNB.jpg',
      original_language: 'en',
      original_title: 'Avengers: Infinity War',
      genre_ids: [12, 28, 14],
      backdrop_path: '/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg',
      adult: false,
      overview:
        'Пока Мстители и их союзники продолжают защищать мир от различных опасностей, с которыми не смог бы справиться один супергерой, новая угроза возникает из космоса: Танос. Межгалактический тиран преследует цель собрать все шесть Камней Бесконечности — артефакты невероятной силы, с помощью которых можно менять реальность по своему желанию. Всё, с чем Мстители сталкивались ранее, вело к этому моменту — судьба Земли никогда ещё не была столь неопределённой.',
      release_date: '2018-04-25'
    },
    {
      vote_count: 479,
      id: 428078,
      video: false,
      vote_average: 6.1,
      title: 'Хроники хищных городов',
      popularity: 105.105,
      poster_path: '/6GOzuWuwcEmys4Vs4U699YiqXE3.jpg',
      original_language: 'en',
      original_title: 'Mortal Engines',
      genre_ids: [878, 28, 12],
      backdrop_path: '/rxYG6Sj95as9rv9wKIHUx6ATWd3.jpg',
      adult: false,
      overview:
        'Прошли тысячелетия после того, как мир настиг апокалипсис. Человечество адаптировалось и теперь живет по новым правилам. Гигантские движущиеся мегаполисы рассекают пустоши и поглощают маленькие города ради ресурсов. Том Нэтсуорти из нижнего уровня великого Лондона оказывается в смертельной опасности, когда на его пути появляется скрывающаяся от закона бунтарка Эстер Шоу. Они не должны были встретиться, но им суждено изменить будущее.',
      release_date: '2018-12-06'
    },
    {
      vote_count: 23,
      id: 505954,
      video: false,
      vote_average: 4.5,
      title: 'Т-34',
      popularity: 98.879,
      poster_path: '/qNBjbjpQC2Rm8M1v0X8jQxb4AnN.jpg',
      original_language: 'ru',
      original_title: 'Т-34',
      genre_ids: [10752, 18, 12],
      backdrop_path: '/vDx8XxfYjkn573bCFGF6SkdM33Q.jpg',
      adult: false,
      overview:
        'Во времена величайших испытаний человечества, когда от каждого действия зависят жизни любимых, два заклятых врага начнут свое противостояние. Оказавшись в плену, вчерашний курсант Ивушкин планирует дерзкий побег. Он собирает свой экипаж и бросает вызов немецким танковым ассам во главе с Ягером. Ради своей любви и Родины он готов идти до конца.',
      release_date: '2018-12-27'
    },
    {
      vote_count: 3,
      id: 494113,
      video: false,
      vote_average: 8,
      title: 'Infisert',
      popularity: 97.581,
      poster_path: '/fX9N4ejnjX2T0pfxaMaMvChC6WL.jpg',
      original_language: 'no',
      original_title: 'Infisert',
      genre_ids: [53, 27],
      backdrop_path: '/xNOppPb8HGXGORqTmCnTM1TlLjy.jpg',
      adult: false,
      overview: '',
      release_date: '2018-12-31'
    },
    {
      vote_count: 3374,
      id: 424694,
      video: false,
      vote_average: 8.2,
      title: 'Богемская рапсодия',
      popularity: 95.62,
      poster_path: '/hGuih2gomFOJzzFnAUsfLF87SVR.jpg',
      original_language: 'en',
      original_title: 'Bohemian Rhapsody',
      genre_ids: [18, 10402],
      backdrop_path: '/pbXgLEYh8rlG2Km5IGZPnhcnuSz.jpg',
      adult: false,
      overview:
        '«Богемская рапсодия» - это чествование группы Queen, их музыки и их выдающегося вокалиста Фредди Меркьюри, который бросил вызов стереотипам и победил условности, чтобы стать одним из самых любимых артистов на планете. Фильм прослеживает головокружительный путь группы к успеху, благодаря их культовым песням и революционному звуку, практически распад коллектива, поскольку образ жизни Меркьюри выходит из-под контроля, и их триумфальное воссоединение накануне концерта Live Aid, ставшем одним из величайших выступлений в истории рок-музыки. Фильм цементирует наследие группы, отношения внутри которой всегда были больше похожи на семейные, и которая продолжают вдохновлять неудачников, мечтателей и любителей музыки по сей день.',
      release_date: '2018-10-24'
    },
    {
      vote_count: 385,
      id: 375588,
      video: false,
      vote_average: 5.9,
      title: 'Робин Гуд: Начало',
      popularity: 91.326,
      poster_path: '/pPP1uEOjpUBo75u00TLrOPKVZ4.jpg',
      original_language: 'en',
      original_title: 'Robin Hood',
      genre_ids: [12, 28, 53],
      backdrop_path: '/AuA50D7T7S7OEVcGo0ZKaMhERn0.jpg',
      adult: false,
      overview:
        'Ветеран Крестовых походов Робин и его командир бросают вызов продажным приспешникам английской короны.',
      release_date: '2018-11-20'
    },
    {
      vote_count: 143,
      id: 375262,
      video: false,
      vote_average: 7.6,
      title: 'Фаворитка',
      popularity: 84.605,
      poster_path: '/cwBq0onfmeilU5xgqNNjJAMPfpw.jpg',
      original_language: 'en',
      original_title: 'The Favourite',
      genre_ids: [18, 36, 35],
      backdrop_path: '/ekWMoBZ4B9rM60INZEh5FAD2HFR.jpg',
      adult: false,
      overview:
        'Фильм рассказывает о политических интригах во время правления королевы Анны — последней представительницы рода Стюартов на престоле Англии.',
      release_date: '2018-11-20'
    }
  ]
};
